### ISSUE TITLE
Incorrect papers titels

### ISSUE THREAD

**Issue by k-haze-nil** [groupoid/groupoid.space#10]
Many authors of papers are omitted, many typos and abbreviations instead of full names.
For example:
  T.Streicher. A groupoid model refutes UIP. 1994             should be
  M. Hofmann T.Streicher. The groupoid model refutes uniqueness of identity proofs. 1994

**Comment by 5HT** [comment]
This is not a bibtex, but rather a hints for googling. Please refer to bibtex file in articles folder.

**Comment by k-haze-nil** [comment]
My bad, I am referring to [https://github.com/groupoid/groupoid.space/blob/master/mltt/infinity/index.html](url) , if you just google all articles you will find many mismatches.

**Comment by 5HT** [comment]
The cutting of author list was made intentionally, so did for article names.
Here are missed correct names: https://github.com/groupoid/groupoid.space/blob/master/tex/articles/infinity/infinity.bib
Therefore, I'm stating this is not a bug.

**Comment by k-haze-nil** [comment]
well, then I have no more complaints
