### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rzrn** [groupoid/groupoid.space#14]
https://github.com/groupoid/groupoid.space/blob/master/mltt/types/propset/index.html (http://groupoid.space/mltt/types/propset/)

This: https://raw.githubusercontent.com/groupoid/infinity/master/priv/propset.ctt.

There should be https://raw.githubusercontent.com/groupoid/infinity/master/priv/prop.ctt, I think.

**Comment by 5HT** [comment]
Thanks for reporting! We splitted propset into prop and set. So meet new page:
http://groupoid.space/mltt/types/prop/  
Previous /propset page is not available anymore.
